title: Blog Robótica Móvil
description: Blog de prácticas de la asignatura Robótica Móvil (Grado en Ingeniería Robótica Software - URJC)

# Tema
theme: jekyll-theme-hacker

# Formato y Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Enlaces limpios y estructura
permalink: pretty
